### ISSUE TITLE
dest: Create directory on the fly if missing

### ISSUE THREAD

**Issue by madskristensen** [geoffrey-ps/geoffrey#4]
The `dest` command doesn't automatically create the directory if it doesn't exist. 

Example:

``` powershell
task less {
    src "less/site.less" |
        less |
        dest "output/site.css"
}
```

If the `output` folder doesn't exist, an exception is thrown:

```
dest : Exception calling "OpenWrite" with "1" argument(s): "Could not find a part of the path
'C:\Users\madsk\Documents\GitHub\geoffrey-samples\less-compiling\output\site.css'."
```

**Comment by sayedihashimi** [comment]
Oh man, I thought I fixed that. I'll take care of it.

**Comment by sayedihashimi** [comment]
@madskristensen ok, just fixed it.

FYI I just added a new file [`install.ps1`](https://github.com/geoffrey-ps/geoffrey/blob/master/install.ps1) that you can use to load the latest version from a local clone. Just run that and it will load the module in your powershell session from source.
