### ISSUE TITLE
Create a combine function

### ISSUE THREAD

**Issue by madskristensen** [geoffrey-ps/geoffrey#9]
Otherwise minification will run on a per-stream basis and not for the entire combined input

**Comment by madskristensen** [comment]
Or perhaps `combine` should be a command you can pipe in so it will combine the input streams to a single one

**Comment by sayedihashimi** [comment]
If the dest is a single file it should be combined. Are you not seeing that?

**Comment by sayedihashimi** [comment]
OK added `combine`, closing this now.
